modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="GNU General Public License"
[[mods]] #mandatory
modId="charcoal_pit" #mandatory
version="3.11.3" #mandatory
displayName="Charcoal Pit" #mandatory
credits="Terrafirmacraft" #optional
authors="EnderiumSmith, [TeamMoeg] dashuaibia" #optional
description='''

'''
[[dependencies.charcoal_pit]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40.0.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.charcoal_pit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
